name: Build

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
    
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Setup Git user info
        run: |
          git config --global user.email "git@40huo.cn"
          git config --global user.name "40huo"

      - name: Install dependencies
        run: |
          npm ci
        env:
          CI: true
      
      - name: Compile and deploy
        run: ./deploy.sh
